permalink: pretty
markdown: kramdown

title: Badania nad zwierzętami
author: Josh Davis &amp; Adam Dobrawy
description:
    Przekonaj swojego posła lub posłankę do zmniejszenia przemocy wobec zwierzet.
url: https://umowy.siecobywatelska.pl
repo: https://github.com/watchdogpolska/umowy
img: img/fb.png

exclude:
    - CNAME
    - CONTRIBUTING.md
    - Gemfile
    - LICENSE
    - README.md
    - Rakefile
    - verify.rb
    - .env
